### ISSUE TITLE
send event by other user details

### ISSUE THREAD

**Issue by ZibaBahari** [Countly/countly-sdk-nodejs#15]
Can i send events with other user details such as a custom field?

because i can not use device_id that is mentioned in below 

_And via SDK you can just create multiple users like this.(countly-sdk-nodejs/examples//bulk_import_example.js)_

**Comment by ar2rsawseen** [comment]
Hello
unfortunately not possible
only device_id is used to identify user, because it is properly indexed to allow high data ingestion rate from SDK

If it is something a bit rarer, you can use app_user update endpoint to update any user (or multiple users) by any query
https://api.count.ly/reference/iapp_usersupdate

**Comment by ArtursKadikis** [comment]
Closing this as this not explicitly an "issue".
